export function SummaryPanel() {
  return (
    <div className="space-y-2">
      <p className="text-sm text-muted-foreground">Generated by AI:</p>
      <div className="bg-muted p-4 rounded-xl">
        <p>This topic covers the structure and traversal of Binary Trees...</p>
      </div>
    </div>
  );
}
